#@ load("@ytt:data", "data")

apiVersion: eventing.knative.dev/v1 
kind: Trigger 
metadata: 
  name: event-display 
spec: 
  broker: default 
  subscriber: 
    ref: 
      apiVersion: serving.knative.dev/v1 
      kind: Service 
      name: event-display 
      namespace: #@ data.values.sessionns
